CREATE TABLE DEPARTMENT(
CODE INT NOT NULL ,
TITLE VARCHAR(30) NOT NULL ,
DEPT_NAME VARCHAR(30) NOT NULL ,
DEPT_ID INT NOT NULL ,
SALARY INT ,
PRIMARY KEY (CODE) ,
UNIQUE (DEPT_NAME,DEPT_ID) ,
CHECK (SALARY > 2000)
);

CREATE TABLE INSTRUCTOR(
NAME VARCHAR(30) NOT NULL ,
CODE INT NOT NULL ,
ID INT DEFAULT 0 ,
PRIMARY KEY (ID)
);

INSERT INTO DEPARTMENT VALUES (11,'PROFESSOR','CS',101,50000);
INSERT INTO DEPARTMENT VALUES (12,'LECTURER','EC',202,25000);

INSERT INTO INSTRUCTOR VALUES ('JACK',11,444);
INSERT INTO INSTRUCTOR VALUES ('JILL',12,554);

SELECT * FROM DEPARTMENT;

SELECT * FROM INSTRUCTOR;


