/* Create a table called NAMES */
CREATE TABLE NAMES (
ID INT PRIMARY KEY ,
NAME VARCHAR(30) NOT NULL
);

/* Create few records in this table */
INSERT INTO NAMES VALUES(1,'Tom');
INSERT INTO NAMES VALUES(2,'Lucy');
INSERT INTO NAMES VALUES(3,'Frank');

/* Display all the records from the table */
SELECT * FROM NAMES;

/* Apply Rollback */
BEGIN TRANSACTION;

INSERT INTO NAMES VALUES(4,'Jane');
INSERT INTO NAMES VALUES(5,'Robert');
SELECT * FROM NAMES;
ROLLBACK;
SELECT * FROM NAMES;

/* Apply Commit */
BEGIN TRANSACTION;

INSERT INTO NAMES VALUES(4,'Jane');
INSERT INTO NAMES VALUES(5,'Robert');
COMMIT;
SELECT * FROM NAMES;

/* Apply Savepoint */
BEGIN TRANSACTION;

SAVEPOINT BeforeMike;
INSERT INTO NAMES VALUES(6,'Mike');
SELECT * FROM NAMES;
ROLLBACK TO BeforeMike;
COMMIT;
SELECT * FROM NAMES;


