/* Create table   */
CREATE TABLE EMPLOYEE(
ID  INT     NOT NULL ,
Name    VARCHAR(20) NOT NULL ,
EMPID INT NOT NULL ,
PRIMARY KEY(ID)
);
CREATE TABLE EMPLOYEEDETAILS(
No  INT     NOT NULL ,
GENDER    VARCHAR(20) NOT NULL ,
AGE INT     NOT NULL ,
EMPID INT ,
PRIMARY KEY(No) ,
FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID)
);

/* Create few records in table */
INSERT INTO EMPLOYEE VALUES(01,'Tom',11);
INSERT INTO EMPLOYEE VALUES(03,'Lucy',33);
INSERT INTO EMPLOYEE VALUES(05,'Frank',55);
INSERT INTO EMPLOYEE VALUES(02,'Jane',22);
INSERT INTO EMPLOYEE VALUES(04,'Robert',44);


INSERT INTO EMPLOYEEDETAILS VALUES(1,'MALE',20,11);
INSERT INTO EMPLOYEEDETAILS VALUES(2,'FEMALE',38,33);
INSERT INTO EMPLOYEEDETAILS VALUES(3,'FEMALE',45,22);



/* Display all the records from the table */
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE EMPID IN (SELECT EMPID FROM EMPLOYEEDETAILS);

SELECT *FROM EMPLOYEE
WHERE EMPID NOT IN (SELECT EMPID FROM EMPLOYEEDETAILS);
